trigger:
- master

pr:
- '*'

pool:
  name: Default

steps:
- script: |
    aws configure set aws_access_key_id AKIAQ376YBZEPMABT4UZ
    aws configure set aws_secret_access_key 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
    aws s3 ls
  displayName: 'List S3 Buckets'
