trigger:
- master


pool:
  name: Default

steps:
- script: |
    aws configure set aws_access_key_id AKIAQ376YBZEPMABT4UZ
    aws configure set aws_secret_access_key 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
    aws configure set region ap-south-1
  displayName: 'Configure AWS CLI'

#- script: |
#    aws s3 ls
#  displayName: 'List AWS S3 Buckets'
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws_service'
    regionName: 'ap-south-1'
    scriptType: 'inline'
    inlineScript: 'aws s3 ls'
  

