
trigger:
- master

pool:
  name: Default
steps:
- script: |
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set region ap-south-1
  displayName: 'Configure AWS CLI'
#- script: |
#    aws s3 ls
#  displayName: 'List AWS S3 Buckets'
env:
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws_service'
    regionName: 'ap-south-1'
    scriptType: 'inline'
    inlineScript: 'aws s3 ls'
  
