jobs:
- job: InstallAWSCli
  displayName: 'Install AWS CLI'
  pool:
    name: Default # Or choose an appropriate image
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install awscli -y
    displayName: 'Install AWS CLI'
